### ISSUE TITLE
[Tracking issue] going farther than the AST

### ISSUE THREAD

**Issue by scrabsha** [iomentum/cargo-breaking#2]
Ideally we should have our own types, that are a bit more abstract than what [`syn`][syn] currently provides. For instance, we don't need to keep the `fn` token when storing a function signature. Similarly, we don't need the `::` when storing an item path.

One of the greatest benefits is that we could do some simple operations during the conversion. A simple example is trait bounds. `cargo-breaking` currently treats the change `T: Send + Sync` to `T: Sync + Send` as a breaking change. As a fix, we could alphabetically sort the bounds when converting data to our own types.

This issue lists what needs to be implemented to fit these goals:
  - [ ] representation of types,
  - [ ] representation of function signatures,
  - [ ] representation of trait items (consts, methods and types),
  - [ ] reworking import representation, if needed.

This list is not exhaustive, some items may be added in the future.

[syn]: https://docs.rs/syn/1.0.73/syn/

**Comment by scrabsha** [comment]
Given the progress of the rustc backend (see #19), this issue is likely to get obsoleted soon.
