### ISSUE TITLE
[Meta] Using the Rustc API by default

### ISSUE THREAD

**Issue by scrabsha** [iomentum/cargo-breaking#34]
Implementation on the `main` branch parses an AST in order to get breaking changes. The `rustc-backend` branch uses the Rustc internal API, which makes changes easier to spot and *way* more precise. In order to use the Rustc API by default, we must implement look for changes in the following items:
  - [ ] functions (we currently only track when the number of arguments change) ([implementation][fn-impl], [tests][fn-tests]),
  - [ ] methods ([implementation][method-impl], [tests][method-tests]),
  - [ ] trait definition ([implementation][trait-def-impl], [tests][trait-def-tests]),
  - [ ] trait implementation ([implementation][trait-impl-impl], [tests][trait-impl-tests]),
  - [ ] struct and enum ([implementation][types-impl], [tests (struct)][struct-tests], [tests (enum)][enum-tests]).

Making all the linked integration tests pass is required in order to merge `rustc-backend` to `main`.

[fn-impl]: https://github.dev/iomentum/cargo-breaking/blob/e9d28fcae0addbfea77a1f2e576909c913136945/src/public_api/functions.rs#L80-L80
[fn-tests]: https://github.com/iomentum/cargo-breaking/blob/e9d28fcae0addbfea77a1f2e576909c913136945/tests/function.rs#L1-L1
[method-impl]: https://github.dev/iomentum/cargo-breaking/blob/e9d28fcae0addbfea77a1f2e576909c913136945/src/public_api/methods.rs#L144-L144
[method-tests]: https://github.dev/iomentum/cargo-breaking/blob/e9d28fcae0addbfea77a1f2e576909c913136945/tests/method.rs#L1-L1
[trait-def-impl]: https://github.dev/iomentum/cargo-breaking/blob/e9d28fcae0addbfea77a1f2e576909c913136945/src/public_api/trait_defs.rs#L108-L108
[trait-def-tests]: https://github.dev/iomentum/cargo-breaking/blob/e9d28fcae0addbfea77a1f2e576909c913136945/tests/trait_defs.rs#L1-L1
[trait-impl-impl]: https://github.dev/iomentum/cargo-breaking/blob/e9d28fcae0addbfea77a1f2e576909c913136945/src/public_api/trait_impls.rs#L151-L151
[trait-impl-tests]: https://github.dev/iomentum/cargo-breaking/blob/e9d28fcae0addbfea77a1f2e576909c913136945/tests/trait_impls.rs#L1-L1
[types-impl]: https://github.dev/iomentum/cargo-breaking/blob/e9d28fcae0addbfea77a1f2e576909c913136945/src/public_api/types.rs#L117-L117
[struct-tests]: https://github.dev/iomentum/cargo-breaking/blob/e9d28fcae0addbfea77a1f2e576909c913136945/tests/structs.rs#L1-L1
[enum-tests]: https://github.dev/iomentum/cargo-breaking/blob/e9d28fcae0addbfea77a1f2e576909c913136945/tests/enum.rs#L1-L1
